@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tk.themcbros.interiormod.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;