@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.interiormod.api.furniture;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;