modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/TheMCBrothers/Interior-Mod/issues"
license="CC BY-NC-ND 4.0"

[[mods]]
    modId="interiormod"
    version="${file.jarVersion}"
    displayName="TheMCBrothers Interior Mod"
    updateJSONURL="https://raw.githubusercontent.com/TheMCBrothers-Manager/Version/master/interiormod_update.json"
    displayURL="https://themcbrothers.net/mods/interiormod"
    logoFile="logo.png"
    authors="TheMCLoveMan, TheMCCrazyMan"
    description='''
    This is a mod that adds interior stuff to your worlds.
    This includes some furniture.
    '''
[[dependencies.interiormod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.interiormod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"

[modproperties.interiormod]
    catalogueItemIcon="interiormod:modern_door"