@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.interiormod.client.models.block.furniture;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;