@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.interiormod.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;