@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tk.themcbros.interiormod.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;